version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  studybud:
    # keep container running even if it dont have task to do
    tty: true
    restart : always
    ports:
     - "8001:8001"
    # run  command at specific file path
    build:
    #  file chosen to be built
     context: .
     dockerfile: Dockerfile
    networks:
      - mynetwork